# -*- coding: utf-8 -*-
"""week4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cTqUtmxbvN8A71Xa0jerxnpaggDCeiQf
"""

pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt 
x = np.arange(50,80,1)
slow = fuzz.trimf(x,[50,50,70])
medium = fuzz.trimf(x,[55,65,80])
medium_fast = fuzz.trimf(x,[60,80,90])
plt.figure()
plt.plot(x,slow,'r', linewidth = 1.5, label = 'slow')
plt.plot(x,medium,'r', linewidth = 1.5, label = 'medium')
plt.plot(x,medium_fast,'r', linewidth = 1.5, label = 'medium_fast')
plt.plot

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl 
food = ctrl.Antecedent(np.arange(0,11,1),'food')
service = ctrl.Antecedent(np.arange(0,11,1),'service')
tip = ctrl.Consequent(np.arange(10,31,1),'tip')
food['poor'] = fuzz.trimf(food.universe,[0,0,5])
food['average'] = fuzz.trimf(food.universe,[0,5,10])
food['good'] = fuzz.trimf(food.universe,[5,10,10])
service['poor'] = fuzz.trimf(service.universe,[0,0,5])
service['average'] = fuzz.trimf(service.universe,[0,5,10])
service['good'] = fuzz.trimf(service.universe,[5,10,10])
tip['poor'] = fuzz.trimf(tip.universe,[10,10,15])
tip['average'] = fuzz.trimf(tip.universe,[15,25,25])
tip['good'] = fuzz.trimf(tip.universe,[15,30,30])
food.view()
service.view()
tip.view()
service['average'].view

rule1 = ctrl.Rule(food['poor'],)

from skfuzzy.control.state import StatePerSimulation
from skfuzzy.control.controlsystem import ControlSystem
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl 
food = ctrl.Antecedent(np.arange(0,11,1),'food')
service = ctrl.Antecedent(np.arange(0,11,1),'service')
tip = ctrl.Consequent(np.arange(10,31,1),'tip')
food['poor'] = fuzz.trimf(food.universe,[0,0,5])
food['average'] = fuzz.trimf(food.universe,[0,5,10])
food['good'] = fuzz.trimf(food.universe,[5,10,10])
service['poor'] = fuzz.trimf(service.universe,[0,0,5])
service['average'] = fuzz.trimf(service.universe,[0,5,10])
service['good'] = fuzz.trimf(service.universe,[5,10,10])
tip['poor'] = fuzz.trimf(tip.universe,[10,10,15])
tip['average'] = fuzz.trimf(tip.universe,[15,20,30])
tip['good'] = fuzz.trimf(tip.universe,[20,30,30])
food.view()
service.view()
tip.view()

rule1 = ctrl.Rule(food['poor']& service['poor'], tip['poor'])
rule2 = ctrl.Rule(food['average']& service['poor'], tip['poor'])
rule3 = ctrl.Rule(food['good']& service['poor'], tip['average'])
rule4 = ctrl.Rule(food['poor']& service['average'], tip['poor'])
rule5 = ctrl.Rule(food['average']& service['average'], tip['average'])
rule6 = ctrl.Rule(food['good']& service['average'], tip['average'])
rule7 = ctrl.Rule(food['poor']& service['good'], tip['poor'])
rule8 = ctrl.Rule(food['average']& service['good'], tip['average'])
rule9 = ctrl.Rule(food['good']& service['good'], tip['average'])

tipping_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9])
tipping = ctrl.ControlSystemSimulation(tipping_ctrl)
tipping.input['food'] = 6.5
tipping.input['service'] = 9.8
tipping.compute()
print(tipping.output['tip'])
tip.view(sim = tipping)